name: saia-a-std

networks:
  saia-a-std:
    driver: bridge

services:
  saia-a-std:
    container_name: saia-a-std
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - "../server/storage:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "4001:3001"
    env_file:
      - .env
    networks:
      - saia-a-std
    extra_hosts:
      - "host.docker.internal:host-gateway"
